defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

base_path: "//gios-asu.github.io/"

markdown: redcarpet
kramdown:
  input: GFM
highlighter: pygments